name: test

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-core:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v2

      - name: ğŸ¦„ Use .NET Core 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.x"

      - name: âœ¨ NuGet Restore
        working-directory: src
        run: dotnet restore

      - name: ğŸ› ï¸ Build FftSharp
        working-directory: src/FftSharp
        run: dotnet build --configuration Release --no-restore

      - name: ğŸ› ï¸ Build Quickstart
        working-directory: src/FftSharp.Quickstart
        run: dotnet build --configuration Release --no-restore

      - name: ğŸ› ï¸ Build Tests
        working-directory: src/FftSharp.Tests
        run: dotnet build --configuration Release --no-restore

      - name: ğŸ§ª Run Tests
        working-directory: src/FftSharp.Tests
        run: dotnet test --no-restore

  build-framework:
    runs-on: windows-latest
    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v1

      - name: âœ¨ Setup NuGet
        uses: nuget/setup-nuget@v1

      - name: ğŸšš Restore NuGet Packages
        working-directory: src
        run: nuget restore

      - name: âœ¨ MSBuild
        uses: microsoft/setup-msbuild@v1.0.3

      - name: ğŸ› ï¸ Build Release
        working-directory: src
        run: msbuild /p:Configuration=Release
